# Site settings
title: Ricardo Sanz
description: 'I love electronics.'
url: 'http://ricardosa.nz'
baseurl: ''
google_analytics: 'UA-64295510-1'
disqus_shortname: 'ricardosanz'

author:
  name: 'Ricardo Sanz'
  email: me@ricardosa.nz
  twitter_username:
  facebook_username:
  github_username: rsre
  linkedin_username: rsanzr
  instagram_username: ricardosa.nz

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
